# k8s-hybrid/base/06-openwebui-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: ai-assistant
spec:
  replicas: 3
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
      - name: open-webui
        image: ghcr.io/open-webui/open-webui:main
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: "http://smart-lb-service:11434"
        - name: WEBUI_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ai-secrets
              key: webui-secret-key
        - name: ENABLE_SIGNUP
          value: "false"
        - name: DEFAULT_MODELS
          value: "phi3:mini,llama3.2:1b,llama3.2:latest,mistral:7b-instruct"
        volumeMounts:
        - name: webui-data
          mountPath: /app/backend/data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "2"
      volumes:
      - name: webui-data
        persistentVolumeClaim:
          claimName: webui-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: open-webui-service
  namespace: ai-assistant
spec:
  selector:
    app: open-webui
  ports:
  - port: 8080
    targetPort: 8080